# -*- coding: utf-8 -*-
"""IRIS_Classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WHSvViFgO1cdnBR1Q1pGLRjY6ADzfRZH
"""

# Commented out IPython magic to ensure Python compatibility.
 import pandas as pd
 import numpy as np
 import seaborn as sns
 import matplotlib.pyplot as plt
#  %matplotlib inline

data = pd.read_csv('iris.csv')
data.head()

len(data['class'])

print(data.columns)

print(data.groupby('class').size())

plt.figure(figsize=(10,10))
plt.subplot(2,2,1)
sns.boxplot(x='class',y='sepallength',data=data)
plt.subplot(2,2,2)
sns.boxplot(x='class',y='sepalwidth',data=data)
plt.subplot(2,2,3)
sns.boxplot(x='class',y='petallength',data=data)
plt.subplot(2,2,4)
sns.boxplot(x='class',y='petalwidth',data=data)

data.isnull().values.any()

data.info()

from sklearn.model_selection import train_test_split
arr = data.values
x = arr[:,0:4]
y = arr[:,4]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0 )

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc = SVC(max_iter = 1000,gamma='auto')
svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)
acc_svc = round(accuracy_score(y_pred,y_test),2)*100
print('Accuracy of svc :',acc_svc)